name: publish

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    container: ubuntu:23.04

    env:
      GH_TOKEN: ${{ github.token }}
      PKG_NAMES: aria2 axel autotools-setup bash bat bison bmake bzip2 b3sum cargo-c cmake coreutils cppcheck ctop curlie curl darkhttpd diffutils dos2unix doxygen ed file findutils flex fzf gawk gping git glow gm4 gmake gnupg gnuplot gh gn gogs gotop gotty gperf grex grep gsed gtar gzip helm hyperfine hugo jq joshuto lazygit libarchive lzip lz4 mediainfo mosh mpg123 nasm ninja nushell openssl patchelf patch pkgconf pkg-config pngquant proot putty pigz qpdf quickjs ripgrep rsync rtmpdump sqlite starship strace tcpdump tealdeer tig timg tmux tree uctags unrar unzip uppm util-linux volta wget xmake xxd xz yasm youtubedr yq zopfli zip p7zip zstd zoxide base16 base64 sysinfo easyutils gettext-tools glib-tools grpc-plugins xsltproc libxml2-utils smake cdrtools procps

    steps:
      - run: apt -y update
      - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update
      - run: ./ppkg install $PKG_NAMES --link-type=static-prefered --install-lib=static
      - run: |
          for PACKAGE_NAME in $(./ppkg ls-installed)
          do
            ./ppkg pack $PACKAGE_NAME -o .
          done

      - run: |
          date +%Y.%m.%d > ts.txt

          TAGNAME="$(cat ts.txt)"

          UPPM_FORMULA_ROOT_DIR="uppm-formula-repository-linux-x86_64-glibc-$TAGNAME"
          UPPM_FORMULA_DIR="$UPPM_FORMULA_ROOT_DIR/formula"

          install -d "$UPPM_FORMULA_DIR"

          for PACKAGE_NAME in $(./ppkg ls-installed)
          do
              RECEIPT_FILEPATH="${HOME}/.ppkg/installed/${PACKAGE_NAME}/.ppkg/receipt.yml"

              PACKAGE_SUMMARY="$("${HOME}/.uppm/installed/yq/bin/yq" .summary "$RECEIPT_FILEPATH")"
              PACKAGE_WEB_URL="$("${HOME}/.uppm/installed/yq/bin/yq" .web-url "$RECEIPT_FILEPATH")"
              PACKAGE_VERSION="$("${HOME}/.uppm/installed/yq/bin/yq" .version "$RECEIPT_FILEPATH")"

              PACKAGE_BIN_FILENAME="$PACKAGE_NAME-$PACKAGE_VERSION-linux-x86_64-glibc.tar.xz"

              PACKAGE_BIN_SHA=$(~/.uppm/installed/coreutils/bin/sha256sum "$PACKAGE_BIN_FILENAME" | cut -d ' ' -f1)

              PACKAGE_BIN_URL="https://github.com/leleliu008/uppm-package-repository-linux-x86_64-glibc/releases/download/${TAGNAME}/${PACKAGE_BIN_FILENAME}"

              cat > "$UPPM_FORMULA_DIR/$PACKAGE_NAME.yml" <<EOF
          summary: $PACKAGE_SUMMARY
          webpage: $PACKAGE_WEB_URL
          version: $PACKAGE_VERSION
          bin-url: $PACKAGE_BIN_URL
          bin-sha: $PACKAGE_BIN_SHA
          EOF
          done

          tar cvJf "$UPPM_FORMULA_ROOT_DIR.tar.xz" "$UPPM_FORMULA_ROOT_DIR"

          ~/.uppm/installed/coreutils/bin/sha256sum *.tar.xz > sha256sums.txt

          cat > notes.md <<EOF
          these packages are created by [ppkg](https://github.com/leleliu008/ppkg).

          these packages have no dependencies other than `glibc`.

          these packages are relocatable which means that you can install them to anywhere.

          ## Environment Variables

          **following environment variables should be set for \`git\` package**

          \`\`\`bash
          export GIT_EXEC_PATH="\$GIT_INSTALL_DIR/libexec/git-core"
          export GIT_TEMPLATE_DIR="\$GIT_INSTALL_DIR/share/git-core/templates"
          \`\`\`

          **following environment variables should be set for \`file\` package**

          \`\`\`bash
          export MAGIC="\$FILE_INSTALL_DIR/share/misc/magic.mgc"
          \`\`\`

          ## sha256sum

          \`\`\`
          $(cat sha256sums.txt)
          \`\`\`
          EOF

          # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
          git -c init.defaultBranch=master init
          git remote add origin ${{ github.repositoryUrl }}

          gh release create "$TAGNAME" *.tar.xz sha256sums.txt --title "$TAGNAME" --notes-file notes.md
